### ISSUE TITLE
No video with supported format and MIME type found

### ISSUE THREAD

**Issue by truthsword** [ShaneIsrael/fireshare#108]
When I click on a video a window opens with:

"No video with supported format and MIME type found."

Yet if I drag that video file into a blank browser (Firefox) tab, it plays. Is this expected?

Thank you!

**Comment by ShaneIsrael** [comment]
Are you running Fireshare via docker and are you properly mounting all the required volumes? It sounds like its unable to create the symlinks to your videos. Are there any errors in the Fireshare docker logs that you can post here?

**Comment by truthsword** [comment]
This is typical...
`2022/08/03 00:01:50 [error] 11#11: *1 open() "/processed/video_links/3345c04e2b2eaaaf9ec0ee7ea15a23c6.mp4" failed (13: Permission denied), client: 172.28.0.1, server: default, request: "GET /_content/video/3345c04e2b2eaaaf9ec0ee7ea15a23c6.mp4 HTTP/1.1", host: "192.168.96.11:8884", referrer: "http://192.168.96.11:8884/"`

This is running on Docker on a Synology NAS... so maybe there are permissions issues somewhere.

Docker compose:
```
version: "3.5"
services:
  fireshare:
    image: shaneisrael/fireshare:latest
    container_name: fireshare
    ports:
      - 8884:80
    volumes:
      - /volume1/docker/fireshare/data:/data
      - /volume1/docker/fireshare/processed:/processed
      - /volume1/testing/clips:/videos
    environment:
      - ADMIN_PASSWORD=admin
    restart: always
```

**Comment by ShaneIsrael** [comment]
Everything looks set up correctly. I would check your folder permissions on 
`/volume1/docker/fireshare/data` and `/volume1/docker/fireshare/processed`

Fireshare is getting permission denied which means that your system isn't allowing docker read/write to those folders.

**Comment by truthsword** [comment]
I'm stumped. Those folders were owned by root. I changed ownership to my primary user and no difference. Then I uploaded another file, and the new folder containing the poster was again owned by root, as was the uploaded video file.

I suspect this is somehow Synology related. In other containers, I must specify the PUID/PGID of my preferred user as an environmental variable, so that those containers (ex. sonarr) run as user, and not as root. I'm unsure if this applies to your container.

Thanks for your help. I'd love to get this running. My only other option is a Raspberry Pi, but I don't see that image supported.

**Comment by ShaneIsrael** [comment]
In docker compose you can try setting the user and group ids to whatever you normally would set them to.


user: $UID:$GID

So for example
```
version: "3.5"
services:
  fireshare:
    image: shaneisrael/fireshare:latest
    container_name: fireshare
    user: 99:100
    ports:
      - 8884:80
    volumes:
      - /volume1/docker/fireshare/data:/data
      - /volume1/docker/fireshare/processed:/processed
      - /volume1/testing/clips:/videos
    environment:
      - ADMIN_PASSWORD=admin
    restart: always
```

if 99 and 100 were your respective user and group id's.
