### ISSUE TITLE
Problem connecting with LDAP

### ISSUE THREAD

**Issue by vylion** [ShaneIsrael/fireshare#225]
**Describe the bug**
I have deployed a Fireshare docker container on my machine, and I have been trying to connect Fireshare to the LDAP provider in [Authentik](https://github.com/goauthentik/authentik). For some reason, whenever I try to login with any user I get the following Traceback output (in the container logs):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fireshare/auth.py", line 17, in auth_user_ldap
    if out[0]:
IndexError: list index out of range
[2023-11-25 00:27:39,766] DEBUG in auth: failure at block1
DEBUG:fireshare:failure at block1
```

I have triple-checked that the credentials and other environment variables are correct; when they aren't, I get an actual error about a connection failure and the container exits.

Trying to do the exact same query and filter with the Linux CLI tool `ldapsearch` (from the `ldap-utils` package) does give a single result, so I am not sure what else could be going wrong, and I don't have the time or environment at the moment to try to clone the repo and debug it myself.

**Expected behavior**
Being able to log in as a user in the LDAP directory.

**Additional context**
I'm running the container on a Debian 12 server. The Authentik container is hosted on a different machine (in the same local network), a Raspberry Pi OS 64-bit based on Debian 12.

**Comment by ShaneIsrael** [comment]
Would be helpful if you could post your docker environment configuration for Fireshare.

**Comment by vylion** [comment]
Sorry! I can't believe I forgot about that. Here it is:

```
version: "3"
services:
  fireshare:
    container_name: fireshare
    image: shaneisrael/fireshare:latest
    ports:
      - "80:80"
    volumes:
      - /docker/fireshare/data:/data
      - /docker/fireshare/processed:/processed
      - /docker/fireshare/videos:/videos
    environment:
      - SECRET_KEY=**********************************
      - MINUTES_BETWEEN_VIDEO_SCANS=5
      - PUID=1000
      - PGID=1000
      - LDAP_ENABLE=true
      - LDAP_URL=ldap://192.168.1.135
      - LDAP_BINDDN=cn=ldapservice,ou=users,dc=ldap,dc=goauthentik,dc=io
      - LDAP_PASSWORD=**************************************************
      - LDAP_BASEDN=dc=ldap,dc=goauthentik,dc=io
      - LDAP_USER_FILTER=(&(|(uid={input})(mail={input}))(objectClass=person))
```
