### ISSUE TITLE
about  video_links

### ISSUE THREAD

**Issue by JiangLongLiu** [ShaneIsrael/fireshare#266]
1. During the migration of the Fireshare Docker container from Synology NAS-A to NAS-B (without copying any files from the 'video_links' directory), I encountered an **HTTP 404** status code when attempting to play a video by clicking on its cover image in Firefox.

2. When uploading a new video to NAS-B via the Fireshare upload button, the functionality worked as expected. Clicking on the cover image successfully played the newly uploaded video, even though there was no corresponding file under `video_links` (e.g., `7b95eefedd286429c17d818a89c4054d.mp4`).

3. After copying some mp4 files from NAS-A's `fireshare/processed/video_links` to NAS-B's `fireshare/processed/video_links`, the videos still failed to play and returned an **HTTP 416** status code.

4. When I entered the Docker container and created a symbolic link named '/processed/videoolinks/3138e6f49252c2ddef2c48ed89901eaa. mp4' pointing to '/videos/uploads/ABC. mp4', the video named ABC still couldn't be played (still with an HTTP 404 status code).
`ln -s /videos/uploads/ABC.mp4 /processed/video_links/3138e6f49252c2ddef2c48ed89901eaa.mp4`

I'm unsure where the issue might lie.

- **When scanning the video library, will the 'fireshare/processed/video_links' directory automatically generate necessary files**?
- **Why are all files in the 'fireshare/processed/video_links' path on NAS-A 0KB in size?**
- **Can I manually generate files in the `video_links` directory on NAS-B using commands, or will they be automatically generated after scanning?**

docker-compose.yml
```
version: '3.7'
services:
  fireshare:
    container_name: fireshare
    image: shaneisrael/fireshare:v1.2.20     
    ports:
      - "8880:80"        
    volumes:
      - ./data:/data         
      - ./processed:/processed  
      - /volume1/test/fireshareSpace:/videos 
    environment:
      - ADMIN_USERNAME=admin     
      - ADMIN_PASSWORD=123   
      - PUID=1026
      - PGID=100      
```
