### ISSUE TITLE
[Feature Request] Add Curl to the Docker Image for Healthchecks

### ISSUE THREAD

**Issue by Krojack** [ShaneIsrael/fireshare#304]
Can't use healthchecks in the Docker image using the following because curl doesn't exists.

```
    healthcheck:
      test:
      - CMD-SHELL
      - curl --fail http://localhost/ || exit 1
      timeout: 10s
      interval: 1m0s
      retries: 5
      start_period: 20s
```
